[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Ajuste para placas ESP32 WROOM32 / ESP32 DevKit
board_build.partitions = default.csv

; Se precisar de logs mais detalhados em depuração:
; build_flags = -DCORE_DEBUG_LEVEL=3
